CREATE TABLE payment (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
  price DECIMAL(30, 8) NOT NULL,
  bankResponse varchar(255),
  primary key (id)
);

create table product (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255),
    name varchar(255),
    price bigint, stock bigint,
    primary key (id)
);
