CREATE TABLE payment (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  price DECIMAL(30, 8) NOT NULL,
  bankResponse varchar(255),
  version int,
  primary key (id)
);

create table product (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
    description varchar(255),
    name varchar(255),
    price bigint, stock bigint,
    version int,
    primary key (id)
);

